import type { SupabaseClient } from "@supabase/supabase-js";

export class SubstitutionQueryError extends Error{}
async function rpc<T>(db:SupabaseClient,name:string,args:Record<string,unknown>):Promise<T>{const {data,error}=await db.rpc(name,args);if(error||!data)throw new SubstitutionQueryError("İşlem tamamlanamadı.");return data as T;}
export const getImportBlockers=(db:SupabaseClient,c:string,y:string)=>rpc<Record<string,unknown>>(db,"get_timetable_import_blockers",{p_campus_name:c,p_academic_year_name:y});
export const getPreparation=(db:SupabaseClient,c:string,y:string,q:{teacherSourceId?:string;dateFrom?:string;dateTo?:string})=>rpc<Record<string,unknown>>(db,"get_substitution_preparation",{p_campus_name:c,p_academic_year_name:y,p_teacher_source_id:q.teacherSourceId??null,p_date_from:q.dateFrom??null,p_date_to:q.dateTo??null});
export const createAbsence=(db:SupabaseClient,c:string,y:string,b:{teacherSourceId:string;dateFrom:string;dateTo:string;absenceScope:"all_day"|"selected_lessons";reasonCode:string;note?:string|null;lessons:unknown[]})=>rpc<Record<string,unknown>>(db,"create_teacher_absence",{p_campus_name:c,p_academic_year_name:y,p_teacher_source_id:b.teacherSourceId,p_date_from:b.dateFrom,p_date_to:b.dateTo,p_reason_code:b.reasonCode,p_note:b.note??null,p_lesson_keys:b.lessons,p_absence_scope:b.absenceScope});
export const listDayLists=(db:SupabaseClient,c:string,y:string)=>rpc<Record<string,unknown>>(db,"list_substitution_day_lists",{p_campus_name:c,p_academic_year_name:y});
export const getDayList=(db:SupabaseClient,c:string,y:string,id:string)=>rpc<Record<string,unknown>>(db,"get_substitution_day_list",{p_list_id:id,p_campus_name:c,p_academic_year_name:y});
export const getCandidates=(db:SupabaseClient,c:string,y:string,id:string)=>rpc<Record<string,unknown>>(db,"get_substitution_task_candidates",{p_task_id:id,p_campus_name:c,p_academic_year_name:y});
export const setTask=(db:SupabaseClient,id:string,b:{teacherSourceId:string|null;unfilledNote?:string|null;expectedVersion:number;overrideAcknowledged?:boolean;overrideNote?:string|null})=>rpc<Record<string,unknown>>(db,"set_substitution_task_resolution",{p_task_id:id,p_teacher_source_id:b.teacherSourceId,p_unfilled_note:b.unfilledNote??null,p_expected_version:b.expectedVersion,p_override_ack:b.overrideAcknowledged??false,p_override_note:b.overrideNote??null});
export const completeList=(db:SupabaseClient,id:string,v:number)=>rpc<Record<string,unknown>>(db,"complete_substitution_day_list",{p_list_id:id,p_expected_version:v});
export const previewDeleteAbsence=(db:SupabaseClient,c:string,y:string,id:string)=>rpc<Record<string,unknown>>(db,"preview_delete_teacher_absence",{p_absence_id:id,p_campus_name:c,p_academic_year_name:y});
export const deleteAbsence=(db:SupabaseClient,id:string,taskIds:string[])=>rpc<Record<string,unknown>>(db,"delete_teacher_absence",{p_absence_id:id,p_expected_task_ids:taskIds});
export const deleteDayList=(db:SupabaseClient,id:string,version:number)=>rpc<Record<string,unknown>>(db,"delete_substitution_day_list",{p_list_id:id,p_expected_version:version});
export const listCompensation=(db:SupabaseClient,c:string)=>rpc<Record<string,unknown>>(db,"list_compensation_settings",{p_campus_name:c});
export const saveCompensation=(db:SupabaseClient,c:string,b:{id?:string|null;name:string;isActive:boolean})=>rpc<Record<string,unknown>>(db,"save_compensation_type",{p_campus_name:c,p_type_id:b.id??null,p_name:b.name,p_is_active:b.isActive});
export const deleteCompensation=(db:SupabaseClient,c:string,id:string)=>rpc<Record<string,unknown>>(db,"delete_compensation_type",{p_campus_name:c,p_type_id:id});
export const addRate=(db:SupabaseClient,c:string,id:string,b:{effectiveFrom:string;unitRate:number})=>rpc<Record<string,unknown>>(db,"add_compensation_rate",{p_campus_name:c,p_type_id:id,p_effective_from:b.effectiveFrom,p_unit_rate:b.unitRate});
export const addPayrollEntry=(db:SupabaseClient,c:string,y:string,b:{teacherSourceId:string;dutyDate:string;compensationTypeId:string;quantity:number;note?:string|null})=>rpc<Record<string,unknown>>(db,"add_manual_payroll_entry",{p_campus_name:c,p_academic_year_name:y,p_teacher_source_id:b.teacherSourceId,p_duty_date:b.dutyDate,p_type_id:b.compensationTypeId,p_quantity:b.quantity,p_note:b.note??null});
export const updatePayrollEntry=(db:SupabaseClient,c:string,y:string,id:string,b:{teacherSourceId:string;dutyDate:string;compensationTypeId:string;quantity:number;note?:string|null})=>rpc<Record<string,unknown>>(db,"update_manual_payroll_entry",{p_campus_name:c,p_academic_year_name:y,p_entry_id:id,p_teacher_source_id:b.teacherSourceId,p_duty_date:b.dutyDate,p_type_id:b.compensationTypeId,p_quantity:b.quantity,p_note:b.note??null});
export const deletePayrollEntry=(db:SupabaseClient,c:string,id:string)=>rpc<Record<string,unknown>>(db,"delete_manual_payroll_entry",{p_campus_name:c,p_entry_id:id});
export const getPayroll=(db:SupabaseClient,c:string,y:string,date:string)=>rpc<Record<string,unknown>>(db,"get_payroll_overview",{p_campus_name:c,p_academic_year_name:y,p_anchor_date:date});
export const closePayroll=(db:SupabaseClient,c:string,y:string,date:string,force=false)=>rpc<Record<string,unknown>>(db,"close_payroll_period",{p_campus_name:c,p_academic_year_name:y,p_anchor_date:date,p_force:force});
